### ISSUE TITLE
tag "comuni" in item 1.2

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#106]
**Describe the bug**

on page Le misure, the item 1.2 contains a tag "comuni"

**Expected behavior**

the correct tag label is "Comuni"

**Screenshots**

<img width="1211" alt="Schermata 2021-11-09 alle 14 51 08" src="https://user-images.githubusercontent.com/79656424/140936264-136bec5f-5f15-4820-80a1-fa0db52d7fe6.png">

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by sebbalex** [comment]
closed by #109
