### ISSUE TITLE
Incorrect "beneficiari" in page "Le misure"

### ISSUE THREAD

**Issue by danieledebernardinDTD** [teamdigitale/padigitale2026.gov.it-site#107]
The "beneficiari" in measures 1.4.3 and 1.4.4 are incorrect.
please double check the whole page, thank you

https://docs.google.com/document/d/1OqltWFNg5IzIW_qn7r5nT95dcNH9Qditj_7PfgC0TGI/edit

**Comment by sebbalex** [comment]
closed by #109
