### ISSUE TITLE
CTA "scopri di più" in home

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#120]
**Describe the bug**

la CTA in homepage nella fase 1 porta ad una pagina 404

**Expected behavior**

al click sulla CTA dovrebbe aprirsi la pagina Le misure
**Screenshots**

![Uploading Schermata 2021-11-10 alle 08.55.45.png…]()

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by lollomag** [comment]
verificato su develop ed il bug non è presente
