### ISSUE TITLE
comportamento del box "contatti" in homepage

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#121]
**Describe the bug**

il box contatti non risponde al click

**Expected behavior**

al click sul titolo del box si dovrebbe aprire il form in overlay
**Screenshots**

<img width="889" alt="Schermata 2021-11-10 alle 09 03 23" src="https://user-images.githubusercontent.com/79656424/141073746-631b44c5-b462-4ee2-beb8-47ca709ba2af.png">

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by lollomag** [comment]
verificato ora su develop ed il bug non è presente, provato anche su più browser
