### ISSUE TITLE
select "Fornitore IT" nel form

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#124]
**Describe the bug**

selezionando la voce "fornitore IT" dalla prima drop-down list nel form, non c'è nessuna variazione

**Expected behavior**

alla selezione della voce "fornitore IT" dovrebbe comparire un campo di testo obbligatorio "nome ente/struttura"
**Screenshots**

<img width="1192" alt="Schermata 2021-11-10 alle 09 16 19" src="https://user-images.githubusercontent.com/79656424/141075907-a8f4f42c-63ef-4d40-a709-4d6b4b36c5b6.png">

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by sebbalex** [comment]
closed by #144
