### ISSUE TITLE
select "altro" nel form

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#125]
**Describe the bug**

alla selezione della voce "altro" nella prima drop-down list del form, si aprono altri 3 campi

**Expected behavior**

alla selezione di "altro" dovrebbero comparire solo i campi di testo "tipo di ente/struttura" e "nome ente/struttura"
**Screenshots**

<img width="1175" alt="Schermata 2021-11-10 alle 09 19 01" src="https://user-images.githubusercontent.com/79656424/141076189-2f750df7-95f3-471e-b95d-3fbdb760b818.png">

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by sebbalex** [comment]
closed by #134
