### ISSUE TITLE
checkbox nel form

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#126]
**Describe the bug**

nel form ci sono due checkbox prima della CTA "invia"

**Expected behavior**

la check box e il testo "acconsento ad essere contattato per comunicazioni specifiche" vanno eliminati.
Al loro posto, inserire la seguente dicitura prima del bottone INVIA --> "Cliccando su INVIA dichiaro di aver letto e compreso l'informativa privacy"

**Screenshots**

<img width="1168" alt="Schermata 2021-11-10 alle 09 20 43" src="https://user-images.githubusercontent.com/79656424/141076482-5355481e-7789-443c-878a-43d12be8822f.png">

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by sebbalex** [comment]
closed by #182
