### ISSUE TITLE
conferma invio del form

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#129]
**Describe the bug**

il messaggio di conferma del form non ha contenuto, comportamento né forma corretti: è grigio, in basso a destra nella pagina, contiene un testo segnaposto e non si chiude al click sulla X
**To Reproduce**

**Expected behavior**

il messaggio deve comparire a centro pagina
se si tratta di messaggi odi conferma, deve avere bordo verde
se si tratta di messaggio di errore, deve essere rosso
se si tratta di conferma, il form deve essere chiuso
se si tratta di messaggio di errore, il form rimane aperto
il testo attuale deve essere sostituito con quelli stabilito per i due casi (conferma/errore)
deve chiudersi al click sulla X

**Screenshots**

<img width="1309" alt="Schermata 2021-11-10 alle 09 23 31" src="https://user-images.githubusercontent.com/79656424/141079585-bccc12f8-1618-413c-90f1-48bd989e0630.png">

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by sebbalex** [comment]
Rimangono aperti i seguenti punti
- deve chiudersi al click sulla X
- il messaggio deve comparire a centro pagina (in alto)

**Comment by sebbalex** [comment]
closed by #194
