### ISSUE TITLE
Link in header

### ISSUE THREAD

**Issue by danieledebernardinDTD** [teamdigitale/padigitale2026.gov.it-site#137]
The label "Dipartimento per la trasformazione digitale" in the header, should have this link https://innovazione.gov.it/ and not https://innovazione.gov.it/dipartimento
<img width="716" alt="Schermata 2021-11-10 alle 10 38 09" src="https://user-images.githubusercontent.com/70584713/141088548-5633ca27-d87c-4095-a434-84128a46eff1.png">

**Comment by sebbalex** [comment]
closed by #142
