### ISSUE TITLE
immagine in pagina Supporto

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#138]
**Describe the bug**

l'immagine mostrata in pagina supporto non è aggiornata

**Expected behavior**

al posto della foto attuale, dovrebbe esserci l'illustrazione appositamente realizzata per questa sezione 
**Screenshots**

![Uploading Schermata 2021-11-10 alle 10.44.37.png…]()

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by lollomag** [comment]
Fix presente su develop
