### ISSUE TITLE
Switch beneficiari

### ISSUE THREAD

**Issue by danieledebernardinDTD** [teamdigitale/padigitale2026.gov.it-site#150]
The beneficiari of 1.7.1 and 1.7.2 need to be switched @sebbalex 

1.7.1 should have Enti iscritti all’albo del servizio civile, while 1.7.2 should have  regioni
<img width="683" alt="Schermata 2021-11-10 alle 17 47 17" src="https://user-images.githubusercontent.com/70584713/141156406-28431a6a-b286-4ecf-af1f-bd5afe09f438.png">

**Comment by lollomag** [comment]
sul file delle misure, i beneficiari sono nel modo in cui sono presenti nell'immagine, potreste darmi una conferma che vanno cambiati ?

**Comment by danieledebernardinDTD** [comment]
Si @lollomag vanno cambiati come indicati nel testo scritto. L'immagine riporta l'attuale situazione che è errata

**Comment by danieledebernardinDTD** [comment]
ciao @lollomag rispetto al file "le misure" il dato dei beneficiari è sbagliato al momento sul sito. te lo riporto di seguito 

https://docs.google.com/document/d/1OqltWFNg5IzIW_qn7r5nT95dcNH9Qditj_7PfgC0TGI/edit

**Comment by sebbalex** [comment]
closed by #168
