### ISSUE TITLE
Add logo of MITD in Footer before logo of DTD

### ISSUE THREAD

**Issue by danieledebernardinDTD** [teamdigitale/padigitale2026.gov.it-site#157]
Currently after logo of EU and the Italian Republic, we only have the logo of the Dipartimento per la trasformazione digitale (DTD)
<img width="639" alt="Schermata 2021-11-11 alle 11 18 26" src="https://user-images.githubusercontent.com/70584713/141281143-324c1346-e5b1-4124-a758-57ed0c4b35b1.png">

Could you please add the logo of the Ministro per l'innovazione tecnologica e la transizione digitale (MITD)? This logo should be to the left of DTD. Thank you

**Comment by sebbalex** [comment]
Fixed by #172
