### ISSUE TITLE
Broken Link from Privacy Policy to return in homepage

### ISSUE THREAD

**Issue by danieledebernardinDTD** [teamdigitale/padigitale2026.gov.it-site#161]
once the privacy policy is opened from the Contact Form, if the user clicks on the homepage banner on top, a white/blank page opens. Video attached with details

https://user-images.githubusercontent.com/70584713/141294068-13268b8d-db54-4f19-b22a-b77a846f889e.mov

**Comment by lollomag** [comment]
presente su develop

**Comment by sebbalex** [comment]
closed by #168
