### ISSUE TITLE
Third support box rendering problem

### ISSUE THREAD

**Issue by sebbalex** [teamdigitale/padigitale2026.gov.it-site#173]
**Description**

Strange glitch appears at third box in Support page, see the screen

**Screenshots**

![Screenshot from 2021-11-11 20-26-59](https://user-images.githubusercontent.com/11008116/141357035-97905256-5027-4bc9-9985-2aa5cfa8ed1e.png)

**Comment by lollomag** [comment]
non riesco a replicarlo, potresti indicarmi come viene fuori ?

**Comment by sebbalex** [comment]
> non riesco a replicarlo, potresti indicarmi come viene fuori ?

dopo la #188 non riscontro più il problema.
