### ISSUE TITLE
Wrong order of "le misure" in homepage

### ISSUE THREAD

**Issue by danieledebernardinDTD** [teamdigitale/padigitale2026.gov.it-site#178]
These two measures are in the wrong order
<img width="1234" alt="Schermata 2021-11-12 alle 09 33 31" src="https://user-images.githubusercontent.com/70584713/141437448-99ad09b6-7e47-43b0-98e4-e8a9b7824425.png">

The correct order should be
1.7.1 Servizio civile digitale
1.7.2 Centri di facilitazione digitale

thanks

**Comment by sebbalex** [comment]
closed by #187
