### ISSUE TITLE
rimuovere controllo dal campo "nome ente/struttura" nei form

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#225]
**Is your feature request related to a problem? Please describe.**

il controllo sul campo definisce come errori le lettere accentate, non accettando quindi alcuni nomi di enti che le contengono

**Describe the solution you'd like**

è necessario rimuovere la feature

**Describe alternatives you've considered**

**Additional context**

**Comment by sebbalex** [comment]
Closed by #225 and #250
