### ISSUE TITLE
change privacy-policy file name 

### ISSUE THREAD

**Issue by danielaiozzo** [teamdigitale/padigitale2026.gov.it-site#241]
abbiamo notato - dopo lo split del form visibile sul ramo di develop - che manca un link per fare in modo che l'utente possa visionare la citata privacy policy prima di premere il pulsante INVIA. 

Necessario quindi: 

1. inserire nell'etichetta di testo presente prima del pulsante INVIA (in entrambi i form) un link di rimando (che si apra in una nuova tab) alla pagina dedicata all'informativa privacy 
2. contestualmente la pagina https://padigitale2026.gov.it/privacy-policy/ dovrebbe diventare */informativa-privacy perciò occorre modificare URL, nome file e etichetta in footer 

![image](https://user-images.githubusercontent.com/15343502/144229485-916d0387-a2ff-448a-a920-1204c2ae4aa4.png)

**Comment by sebbalex** [comment]
Closed by #245 and #247
