### ISSUE TITLE
Automatic accordion open in the page "Le misure"

### ISSUE THREAD

**Issue by Fupete** [teamdigitale/padigitale2026.gov.it-site#262]
On the homepage, clicking on one of the card in the "Le misure" section will take you to the correct anchor (by scrolling down the page) of the "Le misure" page, BUT, ideally that anchor is an accordion that you should find already open no?

Home page section, where u click...
![immagine](https://user-images.githubusercontent.com/6736103/147086907-2cf7c874-9ea1-4e1f-b27d-a2797da7e107.png)

Where it bring you...
![immagine](https://user-images.githubusercontent.com/6736103/147086937-c60543fd-b426-4228-9d27-a284ee546805.png)

How should be...
![immagine](https://user-images.githubusercontent.com/6736103/147086979-6e29075d-90f9-45c8-8cfc-e50b1c1ad8bd.png)

**Comment by sebbalex** [comment]
Closed by #266
