### ISSUE TITLE
Clickable 'area' of the accordion in the page "Le misure" is too small

### ISSUE THREAD

**Issue by Fupete** [teamdigitale/padigitale2026.gov.it-site#263]
The clickable area of the accordions in the page "Le misure" is just the arrow on the right BUT it should be at least also the title of the card if not all the card itself. It is very annoying and unusable on a mobile/touch device. 

Where you can click now... 
![immagine](https://user-images.githubusercontent.com/6736103/147087840-f47c005a-7336-4a91-b95a-3aa3df02a640.png)

At least also the title shoud be interactive...
![immagine](https://user-images.githubusercontent.com/6736103/147087951-2210b57c-1cc0-419c-87e8-3b2d083b8908.png)

If not all the card...
![immagine](https://user-images.githubusercontent.com/6736103/147088048-079d0dfd-f305-4e32-ba69-b5cc518b4f18.png)

**Comment by sebbalex** [comment]
Closed by #265
