### ISSUE TITLE
Anchor links anomaly 

### ISSUE THREAD

**Issue by danieledebernardinDTD** [teamdigitale/padigitale2026.gov.it-site#288]
Anchor links appear to work only when reached from the page "Come funziona". For example if one clicks on "Comuni"
<img width="1111" alt="Schermata 2022-01-26 alle 17 58 37" src="https://user-images.githubusercontent.com/70584713/151210262-b2fde9ff-a3e1-494d-a1b7-cb9d5f18aa20.png">

this url https://padigitale2026.gov.it/misure#comuni works from the page, and filters the page correctly
<img width="1234" alt="Schermata 2022-01-26 alle 18 01 33" src="https://user-images.githubusercontent.com/70584713/151210724-571f4e91-eab1-48d2-9b86-94e83c01f408.png">

However if you open the link normally, it does not work

**Comment by sebbalex** [comment]
closed by #310
