### ISSUE TITLE
wrong color for the link on the page "Supporto"

### ISSUE THREAD

**Issue by frmascia** [teamdigitale/padigitale2026.gov.it-site#335]
the text "accessibilita@innovazione.gov.it" must be updated with the primary blue

<img width="1297" alt="Schermata 2022-03-25 alle 12 52 36" src="https://user-images.githubusercontent.com/100858578/160117218-f20d9024-85c7-411f-8d85-d17a1a28cb0b.png">

**Comment by emnlpstr** [comment]
The bug has been fixed
