### ISSUE TITLE
change request: success page per invio richiesta di assistenza e iscrizione newsletter

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#343]
**Is your feature request related to a problem? Please describe.**

l'invio di una richiesta di assistenza e l'iscrizione alla newsletter attualmente vengono confermate con una notifica a schermo

**Describe the solution you'd like**

deve invece esistere una success page, analoga a quelle previste per i flussi (registrazione, candidatura etc) presenti in area riservata
**Describe alternatives you've considered**

**Additional context**

**Comment by Caracris78** [comment]
contrordine: 
il contatore va lasciato, ma dovrà essere così impostato: 

"ancora disponibili"
cifra in milioni di euro
"su X milioni di euro stanziati"

**Comment by emnlpstr** [comment]
riguardo il primo punto, abbiamo mantenuto il sistema a notifiche.
riguardo il secondo punto, riguarda credo la pagina di dettaglio avviso che è stata sviluppata su salesforce.

**Comment by Caracris78** [comment]
credo che non ci siamo capiti: 
sia per la iscrizione alla newsletter che per l'invio di una richiesta di assistenza (web to case), è NECESSARIO che il processo termini in una success page.
