### ISSUE TITLE
fix: copy change in note legali

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#352]
**Describe the bug**

nella pagina Note legali, c'è un refuso nella frase che segue
<img width="813" alt="Schermata 2022-03-31 alle 19 22 47" src="https://user-images.githubusercontent.com/79656424/161117936-c0090ad4-7655-4147-998c-e5155627762f.png">

**Expected behavior**

il testo deve essere sotituito con: 
"Gli utenti sono quindi liberi di condividere (riprodurre, distribuire, comunicare al pubblico, esporre in pubblico) rappresentare, eseguire e recitare questo materiale con qualsiasi mezzo e formato e modificare (trasformare il materiale e utilizzarlo per opere derivate) per qualsiasi fine, anche commerciale con il solo onere di attribuzione, senza apporre restrizioni aggiuntive.
**Screenshots**

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by emnlpstr** [comment]
Sistemato, è già su develop
