### ISSUE TITLE
Homepage: hero area-CTA behavior

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#60]
**Describe the bug**
le tre CTA nella fascia hero non funzionano

**Expected behavior**
la prima CTA dovrebbe portare alla pagina Opportunità, la seconda e la terza alla pagina Come Funziona

**Screenshots**
<img width="1205" alt="Schermata 2021-11-05 alle 14 27 09" src="https://user-images.githubusercontent.com/79656424/140517536-c76a7193-324e-4955-9e35-b0595ab02f78.png">
<img width="1167" alt="Schermata 2021-11-05 alle 14 26 56" src="https://user-images.githubusercontent.com/79656424/140517543-b5e14831-b5c7-4275-9364-20e45dee3326.png">
<img width="1184" alt="Schermata 2021-11-05 alle 14 26 46" src="https://user-images.githubusercontent.com/79656424/140517546-c8d675a7-48f1-4715-9b72-df85323787d2.png">

**Comment by sebbalex** [comment]
closed by #108
