### ISSUE TITLE
Slim header behavior

### ISSUE THREAD

**Issue by Fupete** [teamdigitale/padigitale2026.gov.it-site#61]
**Describe the bug**
The top-left "Dipartimento per la Trasformazione Digitale" link has a wrong behavior: on desktop has no link connection to the external website, and on mobile the touch it just open the drawer. 

![immagine](https://user-images.githubusercontent.com/6736103/140519685-9afb42b5-3977-4196-be2b-e01c5a254900.png)
![immagine](https://user-images.githubusercontent.com/6736103/140519701-83939c28-dfd4-4217-a863-9be2b8227049.png)

**Expected behavior**
It must have the same behavior of the one implemented on [cloud.italia.it](https://cloud.italia.it): on desktop the text will be connected to the external website https://innovazione.gov.it/dipartimento, and on mobile just the arrow it will open the drawer.

**Comment by sebbalex** [comment]
closed by #108

**Comment by Fupete** [comment]
@sebbalex the issue is resolved on desktop, but not on mobile. Please reopen this.

**Comment by sebbalex** [comment]
> @sebbalex the issue is resolved on desktop, but not on mobile. Please reopen this.

cc @lollomag

**Comment by sebbalex** [comment]
closed by #174
