### ISSUE TITLE
Brand text on mobile homepage

### ISSUE THREAD

**Issue by Fupete** [teamdigitale/padigitale2026.gov.it-site#62]
As expected, just on the homepage, we would like to have the brand title "Prossima PA" and claim "Le opportunità per..." shown just below the mobile header on white background. 

![immagine](https://user-images.githubusercontent.com/6736103/140520226-eef7a96b-54e5-4974-b693-acbb7c11fec5.png)

Expected behavior: use [innovazione.gov.it ](https://innovazione.gov.it)mobile header behavior as a reference.

<img width="415" alt="immagine" src="https://user-images.githubusercontent.com/6736103/140520578-5b918fb0-1942-4b26-95d6-031f388c19d9.png">

**Comment by lollomag** [comment]
fix su develop

**Comment by sebbalex** [comment]
closed by #137
