### ISSUE TITLE
Timeline in "Come funzione" deve finire dopo 

### ISSUE THREAD

**Issue by danieledebernardinDTD** [teamdigitale/padigitale2026.gov.it-site#65]
**Timeline ha troppi elementi**
<vanno tolti i blocchi 3 e 4 dalla timeline->
<img width="750" alt="Schermata 2021-11-05 alle 15 18 14" src="https://user-images.githubusercontent.com/70584713/140524890-3ab37160-d555-4eb4-bd93-a2d10b8c9150.png">

**Comment by sebbalex** [comment]
closed by #110
