### ISSUE TITLE
Home "Supporto", preview FAQ sbagliata

### ISSUE THREAD

**Issue by danieledebernardinDTD** [teamdigitale/padigitale2026.gov.it-site#66]
**Verticale "Supporto", preview FAQ sbagliata**

La preview delle 3 FAQ nella verticale di Supporto è sbagliata, andrebbe aggiornata con il testo vero
<img width="1277" alt="Schermata 2021-11-05 alle 15 34 11" src="https://user-images.githubusercontent.com/70584713/140527709-36fb3f14-e86f-4de9-ae96-c2baa6720b9d.png">

**Comment by sebbalex** [comment]
closed by #104
