### ISSUE TITLE
On mobile the secondary menu on "Come funziona" should be centered

### ISSUE THREAD

**Issue by Fupete** [teamdigitale/padigitale2026.gov.it-site#67]
**Describe the bug**
The secondary menu voices, just below the hero, and just for the mobile breakpoints, should be centered in horizontal.

![immagine](https://user-images.githubusercontent.com/6736103/140527699-a02891b9-e0cb-4072-a893-c1bfce17ad0f.png)

**Expected behavior**
Titles (eg. APPROFONDISCI) and links (eg. Il calendario) should be centered on the page. 
Reference: [innovazione.gov.it/dipartimento]( https://innovazione.gov.it/ministro/ )

**Comment by sebbalex** [comment]
closed by #111
