### ISSUE TITLE
Main menu behaviour

### ISSUE THREAD

**Issue by danielaiozzo** [teamdigitale/padigitale2026.gov.it-site#68]
atterrando sulla pagina "opportunità" **dalla CTA di home "scopri tutte le opportunità"**,  l'etichetta di menu di primo livello **NON è sottolineata** 

![image](https://user-images.githubusercontent.com/15343502/140529626-02ad743c-a973-4a12-9420-7193e2a3b2c9.png)

**Comment by sebbalex** [comment]
closed by #113
