### ISSUE TITLE
Hero content layout should be normalized on second level sections

### ISSUE THREAD

**Issue by Fupete** [teamdigitale/padigitale2026.gov.it-site#76]
Pay attetion to: 

- space between title and top menu bar > should be equal (72px? 96px?) 
- space between title and text and left page margin > should be equal, one bootstrap column (1/12)
- text column width > should be equal (5 or 6 bootstrap columns)
- text height exception > for the page "Come funziona" we can think to use a 18px text for the subtitle to reduce height of the hero
- image width for the page "Come funziona" > please evaluate to resize/cut the image more squared

Le misure
![immagine](https://user-images.githubusercontent.com/6736103/140714279-96eab3d8-fcd8-4ce1-a21f-f24baf1ab609.png)

Come funziona
![immagine](https://user-images.githubusercontent.com/6736103/140714325-8a396c57-f454-4ffd-a78c-2ef82ead13b6.png)

Supporto
![immagine](https://user-images.githubusercontent.com/6736103/140714374-b74b0297-fda4-4bfb-8401-404f14927933.png)

**Comment by lollomag** [comment]
presente su develop
