### ISSUE TITLE
Form select weird behaviour

### ISSUE THREAD

**Issue by Fupete** [teamdigitale/padigitale2026.gov.it-site#77]
**Describe the bug**
In the form "Rimani aggiornato" the select "Argomento messaggio" has a weird behaviour. 

**To Reproduce**
1. select a voice
2. reopen the select to change the selection
3. you can view all the select voices "blu" active... and not just the previous selected one.

**Screenshots**
![immagine](https://user-images.githubusercontent.com/6736103/140715568-331b0fc2-d165-4089-9c00-399b06f05970.png)

**Comment by sebbalex** [comment]
closed by #112
