### ISSUE TITLE
privacy flags -  Form

### ISSUE THREAD

**Issue by danielaiozzo** [teamdigitale/padigitale2026.gov.it-site#79]
gli attuali flag vanno eliminati;

inserire la seguente dicitura **prima del bottone INVIA** --> "Cliccando su INVIA dichiaro di aver letto e compreso l'informativa privacy"

**Comment by lollomag** [comment]
non è presente alcuna indicazione nelle grafiche prodotte, deve essere un testo semplice sopra il button ? Nel caso facciamo un passaggio con Pietro Salamone per stili e gestioni grafiche

**Comment by Caracris78** [comment]
testo semplice sopra il button va bene

**Comment by sebbalex** [comment]
closed by #171
