### ISSUE TITLE
CTA behavior in homepage section

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#83]
**Describe the bug**

CTA "scopri di più" opens a new tab with the same page

**Expected behavior**

one click on the CTA should open Come Funziona page

**Screenshots**

<img width="1219" alt="Schermata 2021-11-08 alle 12 23 12" src="https://user-images.githubusercontent.com/79656424/140734055-2a377b58-0776-4f4a-b9b2-a73c26331bc7.png">

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by sebbalex** [comment]
closed by #108
