### ISSUE TITLE
Link to Italia digitale 2026

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#84]
**Describe the bug**

the CTA "vai al sito" in homepage opens a new tab with the same page

**Expected behavior**

one click on the CTA should open the link: https://innovazione.gov.it/dipartimento/focus/italia-digitale-2026/ in a new tab

**Screenshots**

<img width="1205" alt="Schermata 2021-11-08 alle 12 30 18" src="https://user-images.githubusercontent.com/79656424/140734794-1eeea935-9f7b-41e1-b876-2c3012ff0a38.png">

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by lollomag** [comment]
Fix presente su develop
