### ISSUE TITLE
menu selection on page FAQ

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#85]
**Describe the bug**

on page "domande frequenti" no menu item is selected

**Expected behavior**

the item Supporto should be selected (underlined)

**Screenshots**

<img width="871" alt="Schermata 2021-11-08 alle 12 36 50" src="https://user-images.githubusercontent.com/79656424/140735721-6d2f6cf4-79ef-4dbf-b468-e484517fa4f2.png">
![Uploading Schermata 2021-11-08 alle 12.36.50.png…]()

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by sebbalex** [comment]
closed by #187
