### ISSUE TITLE
box "Contatti" behavior

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#86]
**Describe the bug**

the box has no behavior (all pages)

**Expected behavior**

click on "contatti" should open the overlay form
**Screenshots**

<img width="1064" alt="Schermata 2021-11-08 alle 12 40 20" src="https://user-images.githubusercontent.com/79656424/140736058-e969e08b-4e2d-4456-8b56-7bde9adb220b.png">

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by sebbalex** [comment]
closed by #112
