### ISSUE TITLE
drop-down list "le misure" behavior

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#87]
**Describe the bug**

in the drop-down list on page Le Misure, selecting Aziende Ospedaliere, you get no results

**Expected behavior**

**Screenshots**

<img width="1273" alt="Schermata 2021-11-08 alle 12 43 31" src="https://user-images.githubusercontent.com/79656424/140736567-c811cae7-4023-4faf-bb78-d8010b6830e0.png">

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by lollomag** [comment]
Fix presente su develop
