### ISSUE TITLE
menu item selection "le misure"

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#88]
**Describe the bug**

if you land on page "le misure" from the CTA in homepage "scopri tutte le misure", the page is loaded with no menu item selected. 

**Expected behavior**

**Screenshots**

<img width="1280" alt="Schermata 2021-11-08 alle 12 49 49" src="https://user-images.githubusercontent.com/79656424/140737056-671f6de1-a531-4a6d-9ab2-bc018174cf88.png">
<img width="1220" alt="Schermata 2021-11-08 alle 12 47 38" src="https://user-images.githubusercontent.com/79656424/140737066-3cc93a97-05f7-4686-a581-6aa2e03314b0.png">

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by lollomag** [comment]
Fix presente su develop

**Comment by Caracris78** [comment]
il bug non è stato risolto: la pagina Le misure viene ancora caricata senza che la corrispondente voce di menu risulti  selezionata (sottolineata)

**Comment by sebbalex** [comment]
closed by #113
