### ISSUE TITLE
link "Presentazione progetto"

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#89]
**Describe the bug**

all the links "presentazione progetto" in the page Le misure accordion are not working

**Expected behavior**

the link should open page Come funziona with the Presentazione progetti section in focus
**Screenshots**

<img width="1171" alt="Schermata 2021-11-08 alle 12 58 56" src="https://user-images.githubusercontent.com/79656424/140738258-9f4c2ab7-4787-46ce-80db-b4dd18c8b6eb.png">
<img width="1256" alt="Schermata 2021-11-08 alle 12 58 32" src="https://user-images.githubusercontent.com/79656424/140738266-d25aa827-732a-4966-ab85-b31b16317160.png">

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by sebbalex** [comment]
Closed by #102
