### ISSUE TITLE
link "pacchetti standard" behavior

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#90]
**Describe the bug**

all the links "pacchetti standard" in the page Le misure accordion are not working

Expected behavior

the link should open page Come funziona with the Soluzioni standard section in focus

**Screenshots**

<img width="1274" alt="Schermata 2021-11-08 alle 13 00 01" src="https://user-images.githubusercontent.com/79656424/140738789-8281ae65-43c5-4658-8c50-77052bb375db.png">
<img width="1203" alt="Schermata 2021-11-08 alle 12 59 46" src="https://user-images.githubusercontent.com/79656424/140738793-49f309d8-cef3-473c-becf-b4935ca1fcf2.png">

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by sebbalex** [comment]
Closed by #102
