### ISSUE TITLE
behavior of link "scopri l'iniziativa"

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#92]
**Describe the bug**

click on the link (in footer) scrolls up the page

**Expected behavior**

it should open page Come Funziona and scroll to "attori" section

**Screenshots**

<img width="1122" alt="Schermata 2021-11-08 alle 13 09 57" src="https://user-images.githubusercontent.com/79656424/140739813-86057ccb-4d4f-4f05-b244-1393f977cfeb.png">
<img width="1352" alt="Schermata 2021-11-08 alle 13 07 45" src="https://user-images.githubusercontent.com/79656424/140739817-c803c6f5-13b1-421e-9166-a54d2f086337.png">

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by sebbalex** [comment]
Closed by #102
