### ISSUE TITLE
FAQ preview boxes

### ISSUE THREAD

**Issue by Caracris78** [teamdigitale/padigitale2026.gov.it-site#93]
**Describe the bug**

the 3 FAQ preview boxes on page Supporto are not working

**Expected behavior**

click on each box should open page Domande frequenti and explode the corresponding item /FAQ
**Screenshots**

<img width="1283" alt="Schermata 2021-11-08 alle 13 13 49" src="https://user-images.githubusercontent.com/79656424/140740270-fbb5c29e-caa1-4793-acfc-d68697b66909.png">

**Smartphone (please complete the following information):**

**Additional context**
Add any other context about the problem here.-->

**Comment by sebbalex** [comment]
closed by  #104
